### ISSUE TITLE
Telegram still there ... ?

### ISSUE THREAD

**Issue by olvier** [1RandomDev/whosinmylan#2]
Cheers.

You are coming from WatchYourLAN, where Telegram was an option for sending notification.

Is it totally gone, or is it still somewhere present in the code?
I'm totally nw to gotify, and it doesn't fit into my usecase :)

I use ntfy.sh (for apple watch), telegram, apprise (awesome!) or join. Every service has its own usecase, but gotify doesn't fit in anywhere :)

Is there any option for another one?

Cheers.

**Comment by 1RandomDev** [comment]
> You are coming from WatchYourLAN

My project isn't a fork of WatchYourLAN, it's just a project that does a similar thing.

And no currently there's only support for gotify, that's because the WatchYourLAN uses [shoutrrr](https://github.com/containrrr/shoutrrr) for notifications which unfortunately only works in go.

But thx thats awesome! Apprise looks like a really great and reliable solution that could replace the current notification system and it supports almost every notification provider imaginable.

**Comment by 1RandomDev** [comment]
Added support for apprise in v1.3.0

**Comment by olvier** [comment]
That's so f*ckin awesome!

What about multiple urls?
in changedetection.io it's just a text-field, and every line is a notification-"channel".

But for now, read the first line again :)

**Comment by 1RandomDev** [comment]
Having multiple notification urls would be possible, but probably a bit confusing to configure just via environment variables. I'll see if I find a good way that easily lets the user input multiple urls.

**Comment by olvier** [comment]
> Added support for apprise in v1.3.0

Works like a charm. Thank you for implementation!

Other question:
In the Telegram-Message, the URL still refers to gotify url, but not not whosinmylan-url.
The local IP is the same, but the port is different.

I also deleted `data.db`, but it didn't changed anything.

Any idea?

**Comment by 1RandomDev** [comment]
> In the Telegram-Message, the URL still refers to gotify url, but not not whosinmylan-url.

Don't really understand what you mean. The URL that's shown in the message is configured via `WEBUI_URL`. All the environment variables that start with `GOTIFY_` were replaced with `APPRISE_URL` and shouldn't do anything in the latest version.

> I also deleted data.db, but it didn't changed anything.

The database has nothing to do with the configuration, it's only used for storing the known devices.

**Comment by olvier** [comment]
> > In the Telegram-Message, the URL still refers to gotify url, but not not whosinmylan-url.
> 
> Don't really understand what you mean. The URL that's shown in the message is configured via `WEBUI_URL`. All the environment variables that start with `GOTIFY_` were replaced with `APPRISE_URL` and shouldn't do anything in the latest version.
> 

In my case, it doesn't show the url (IP:port 8484) of the service itself, it shows the url (IP:port 8083) of gotify.


> > I also deleted data.db, but it didn't changed anything.
> 
> The database has nothing to do with the configuration, it's only used for storing the known devices.

I assumed so, but tried, just to be sure.

**Comment by 1RandomDev** [comment]
Well that's really weird. The notification should show exactly what you set in `WEBUI_URL`. If you use docker compose really make sure that you recreate the container instead of just restarting it. Otherwise the variables aren't updated.

**Comment by olvier** [comment]
My fault, i missed that `WEBUI_URL` thing.
There was the wrong port (from gotify), and i didn't used `WEBUI_PORT="8484"`, because it has a default.

But: I still need to put the (right) port into the `WEBUI_URL`, to get linked to the right location.
So maybe `WEBUI_PORT` is not needed here?

**Comment by 1RandomDev** [comment]
Oh these two variables have nothing to do with each other. As described in the [Configuration](https://github.com/1RandomDev/whosinmylan#configuration) section `WEBUI_PORT` is just the port the webserver will listen to. `WEBUI_URL` currently is only used for the notification and is the whole URL you use in the browser to access the webinterface. In my case over a local domain and a reverse proxy so I would use `WEBUI_URL=http://whosinmylan.my-server.home`. If you access the webinterface via ip:port just use `WEBUI_URL=http://192.168.1.xx:8484` as the URL. Hope that explains the difference between port and URL.

**Comment by olvier** [comment]
Ah, you are right.
From the point of external hosted view/domain it absolutely makes sense.

Thank you so much for "the app", I really love it and it's so much better than "the other" one ;)
